services:
  - type: web
    name: pos-backend
    runtime: node
    repo: https://github.com/madal1yev/pos
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/server.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true

