const LANG = {
  uz: {
    name: "O'zbek",
    flag: '🇺🇿',
    start: 'Assalomu alaykum, *{name}*! 👋\n\n*🍽️ Do\'kon botiga xush kelibsiz!*',
    chooseLang: '🌐 *Tilni tanlang:*',
    products: '🛍️ Mahsulotlar',
    search: '🔍 Qidirish',
    myCart: '🛒 Savat ({count})',
    myOrders: '📋 Buyurtmalarim',
    back: '⬅️ Orqaga',
    backMain: '⬅️ Bosh sahifa',
    noProducts: 'Mahsulotlar yo\'q',
    categories: '📂 *Kategoriyalar:*',
    categoryProducts: 'Kategoriya mahsulotlari',
    allProducts: '📋 Barcha mahsulotlar ({count})',
    noProductsCat: 'Bu kategoriyada mahsulot yo\'q',
    productDetail: '📦 *{name}*\n💰 *{price}*\n📦 {stock} dona {status}\n{description}',
    inStock: '✅',
    lowStock: '⚠️ Kam',
    outOfStock: '❌ Tugagan',
    addToCart: '🛒 Savatga',
    viewCart: '📋 Savat ({count})',
    notFound: 'Topilmadi',
    notFoundSearch: '🔍 \"{query}\" bo\'yicha topilmadi',
    foundSearch: '🔍 *{count}* ta topildi:',
    addToCartQty: '🛒 *{name}* — *{price}*\n📦 {stock} dona\nNechta?',
    cancel: '❌ Bekor',
    error: '❌ Xatolik',
    onlyStock: '❌ Faqat {stock} dona qoldi',
    addedToCart: '✅ *{name}* ({qty}) qo\'shildi!\n🛒 Savat: *{count}* ta — *{total}*',
    continue: '🛍️ Davom',
    confirmOrder: '✅ Buyurtma berish',
    cartEmpty: '🛒 Savat bo\'sh\nMahsulot tanlang',
    cart: '🛒 *Savatingiz:* ({count} ta)\n\n{items}\n💰 *Jami: {total}*',
    cartItem: '{i}. *{name}*\n   {qty} x {price} = *{subtotal}*\n',
    remove: '🗑️ Olib tashlash',
    clearCart: '🗑️ Tozalash',
    cartCleared: '🗑️ Savat tozalandi',
    orderSummary: '🧾 *Buyurtma:*\n{items}\n💰 *Jami: {total}*',
    orderItem: '{i}. {name} — {qty} x {price} = *{subtotal}*\n',
    customer: '👤 {name}',
    confirm: 'Tasdiqlaysizmi?',
    askDelivery: '🚚 Yetkazib berish?',
    deliveryYes: '✅ Yetkazilsin',
    deliveryNo: '❌ O\'zim olaman',
    deliveryAddress: '📍 Manzilni yozing:',
    sendLocation: '📍 Lokatsiya',
    locationPrompt: '📍 Lokatsiya yuboring (📎 → Joylashuv)',
    pickup: '🏪 Do\'kondan',
    deliveryText: '🚚 {address}',
    orderSuccess: '✅ *Buyurtma qabul qilindi!* 🎉\n📋 `{invoice}`\n💰 *{total}*\n{delivery}\n📞 @{admin}',
    newOrder: '🔔 *YANGI BUYURTMA!* #{invoice}\n{items}\n👤 {customer}\n💰 *{total}*\n{delivery}',
    orderError: '❌ Xatolik. @{admin} ga murojaat qiling',
    newOrderBtn: '🛍️ Yangi buyurtma',
    searchPrompt: '🔍 Mahsulot nomini yozing:',
    enterNumber: '❌ Son kiriting',
    adminOnly: '❌ Ruxsat yo\'q',
    noOrders: 'Buyurtmalar yo\'q',
    ordersList: '📋 *Oxirgi buyurtmalar:*\n',
    orderItem_short: '{i}. `{invoice}` 👤 {customer} 💰 {amount}\n',
    noDeliveries: 'Yetkazib berish yo\'q',
    deliveriesList: '🚚 *Yetkazishlar:*\n',
    deliveryItem: '{i}. `{invoice}` 👤 {customer} 📍 {address}\n',
    help: '📚 /start /products /cart /myorders /lang',
    langChanged: '✅ {lang}',
    errorOccurred: '❌ Xatolik',
    myOrders_title: '📋 *Buyurtmalarim*',
    noOrdersUser: 'Buyurtmalaringiz yo\'q',
    stockCheck: '📊 Zaxira: ✅ {available} | ⚠️ {low} | ❌ {out}',
    stockOut: '❌ Tugagan:\n',
    stockLow: '⚠️ Kam:\n',
    stockItem: '  • {name} ({stock})\n',
    stockOutItem: '  • {name}\n',
    productsList: '📋 *{title}* ({count})\n{list}',
    selectCategory: '📂 *Kategoriyalar:*',
    phonePrompt: '📞 Telefon:',
    addressPrompt: '📍 Manzil:',
    cancelOrder: '❌ Bekor qilish',
    cancelConfirm: 'Buyurtmani bekor qilishni tasdiqlaysizmi?',
    cancelled: '✅ Buyurtma bekor qilindi',
    cancelFail: '❌ Buyurtmani bekor qilib bo\'lmadi',
    promoCode: '🏷️ Promo kod',
    promoPrompt: '🏷️ Promo kodingizni yozing:',
    promoApplied: '✅ Promo kod qo\'llanildi! Chegirma: {discount}',
    promoInvalid: '❌ Promo kod noto\'g\'ri yoki muddati o\'tgan',
  },

  ru: {
    name: 'Русский',
    flag: '🇷🇺',
    start: 'Здравствуйте, *{name}*! 👋\n\n*🍽️ Добро пожаловать!*',
    chooseLang: '🌐 *Выберите язык:*',
    products: '🛍️ Товары',
    search: '🔍 Поиск',
    myCart: '🛒 Корзина ({count})',
    myOrders: '📋 Мои заказы',
    back: '⬅️ Назад',
    backMain: '⬅️ Главная',
    noProducts: 'Товаров нет',
    categories: '📂 *Категории:*',
    categoryProducts: 'Товары категории',
    allProducts: '📋 Все товары ({count})',
    noProductsCat: 'В этой категории нет товаров',
    productDetail: '📦 *{name}*\n💰 *{price}*\n📦 {stock} шт {status}\n{description}',
    inStock: '✅',
    lowStock: '⚠️ Мало',
    outOfStock: '❌ Нет',
    addToCart: '🛒 В корзину',
    viewCart: '📋 Корзина ({count})',
    notFound: 'Не найдено',
    notFoundSearch: '🔍 \"{query}\" не найдено',
    foundSearch: '🔍 Найдено *{count}*:',
    addToCartQty: '🛒 *{name}* — *{price}*\n📦 {stock} шт\nСколько?',
    cancel: '❌ Отмена',
    error: '❌ Ошибка',
    onlyStock: '❌ Осталось {stock} шт',
    addedToCart: '✅ *{name}* ({qty}) добавлен!\n🛒 Корзина: *{count}* — *{total}*',
    continue: '🛍️ Далее',
    confirmOrder: '✅ Заказать',
    cartEmpty: '🛒 Корзина пуста',
    cart: '🛒 *Корзина:* ({count})\n\n{items}\n💰 *Итого: {total}*',
    cartItem: '{i}. *{name}*\n   {qty} x {price} = *{subtotal}*\n',
    remove: '🗑️ Убрать',
    clearCart: '🗑️ Очистить',
    cartCleared: '🗑️ Корзина очищена',
    orderSummary: '🧾 *Заказ:*\n{items}\n💰 *Итого: {total}*',
    orderItem: '{i}. {name} — {qty} x {price} = *{subtotal}*\n',
    customer: '👤 {name}',
    confirm: 'Подтверждаете?',
    askDelivery: '🚚 Доставка?',
    deliveryYes: '✅ Доставить',
    deliveryNo: '❌ Самовывоз',
    deliveryAddress: '📍 Напишите адрес:',
    sendLocation: '📍 Локация',
    locationPrompt: '📍 Отправьте локацию (📎 → Локация)',
    pickup: '🏪 Самовывоз',
    deliveryText: '🚚 {address}',
    orderSuccess: '✅ *Заказ принят!* 🎉\n📋 `{invoice}`\n💰 *{total}*\n{delivery}\n📞 @{admin}',
    newOrder: '🔔 *НОВЫЙ ЗАКАЗ!* #{invoice}\n{items}\n👤 {customer}\n💰 *{total}*\n{delivery}',
    orderError: '❌ Ошибка. Свяжитесь с @{admin}',
    newOrderBtn: '🛍️ Новый заказ',
    searchPrompt: '🔍 Введите название:',
    enterNumber: '❌ Введите число',
    adminOnly: '❌ Нет прав',
    noOrders: 'Нет заказов',
    ordersList: '📋 *Последние заказы:*\n',
    orderItem_short: '{i}. `{invoice}` 👤 {customer} 💰 {amount}\n',
    noDeliveries: 'Нет доставок',
    deliveriesList: '🚚 *Доставки:*\n',
    deliveryItem: '{i}. `{invoice}` 👤 {customer} 📍 {address}\n',
    help: '📚 /start /products /cart /myorders /lang',
    langChanged: '✅ {lang}',
    errorOccurred: '❌ Ошибка',
    myOrders_title: '📋 *Мои заказы*',
    noOrdersUser: 'У вас нет заказов',
    stockCheck: '📊 Склад: ✅ {available} | ⚠️ {low} | ❌ {out}',
    stockOut: '❌ Нет в наличии:\n',
    stockLow: '⚠️ Мало:\n',
    stockItem: '  • {name} ({stock})\n',
    stockOutItem: '  • {name}\n',
    productsList: '📋 *{title}* ({count})\n{list}',
    selectCategory: '📂 *Категории:*',
    phonePrompt: '📞 Телефон:',
    addressPrompt: '📍 Адрес:',
    cancelOrder: '❌ Отменить',
    cancelConfirm: 'Подтвердите отмену заказа?',
    cancelled: '✅ Заказ отменен',
    cancelFail: '❌ Не удалось отменить заказ',
    promoCode: '🏷️ Промо код',
    promoPrompt: '🏷️ Введите промо код:',
    promoApplied: '✅ Промо код применен! Скидка: {discount}',
    promoInvalid: '❌ Промо код недействителен',
  },
};

function t(lang, key, vars = {}) {
  let str = (LANG[lang] || LANG.uz)[key] || key;
  for (const [k, v] of Object.entries(vars)) {
    str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
  }
  return str;
}

module.exports = { t, LANG };
