const LANG = {
  uz: {
    name: "O'zbek",
    flag: '🇺🇿',
    start: "Assalomu alaykum, *{name}*! 👋\n\n🍽️ *Oziq-ovqat do'koniga xush kelibsiz!*\n\nMen sizga mahsulotlar haqida ma'lumot berishim va buyurtma qilishda yordam bera olaman.",
    chooseLang: '🌐 *Tilni tanlang:*',
    mainMenu: '📌 Nima qilmoqchisiz?',
    products: '🛍️ Mahsulotlar',
    search: '🔍 Qidirish',
    myCart: '🛒 Savatim',
    myOrders: '📋 Buyurtmalarim',
    back: '⬅️ Orqaga',
    backMain: '⬅️ Bosh sahifa',
    noProducts: 'Hozircha mahsulotlar mavjud emas. 😔',
    categories: '📂 *Kategoriyalar:*\n\nQaysi kategoriyadan mahsulot ko\'rmoqchisiz?',
    categoryProducts: 'Kategoriya mahsulotlari',
    allProducts: 'Barcha mahsulotlar',
    noProductsCat: 'Bu kategoriyada mahsulotlar yo\'q. 😔',
    productDetail: '📦 *{name}*\n\n{image}{brand}📂 Kategoriya: {category}\n💰 Narxi: *{price}*\n📏 O\'lchov: {unit}\n📦 Zaxira: *{stock} dona* {status}\n{description}',
    brand: '🏷️ Brend: {brand}\n',
    imageLink: '🖼️ Rasm: [Ko\'rish]({url})\n',
    inStock: '✅ Mavjud',
    lowStock: '⚠️ Kam qoldi',
    outOfStock: '❌ Tugagan',
    addToCart: '🛒 Savatga qo\'shish',
    viewCart: '📋 Savatimni ko\'rish',
    notFound: 'Mahsulot topilmadi',
    notFoundSearch: '🔍 "{query}" bo\'yicha hech narsa topilmadi.',
    foundSearch: '🔍 "{query}" bo\'yicha *{count}* ta mahsulot topildi:',
    addToCartQty: '🛒 *{name}* savatga qo\'shilmoqda\n\n💰 Narxi: *{price}*\n📦 Mavjud: *{stock} dona*\n\nNecha dona kerak?\n💡 *Raqamni bosing yoki o\'zingiz kiriting (masalan: 5)*',
    cancel: '❌ Bekor qilish',
    error: '❌ Xatolik yuz berdi',
    onlyStock: '❌ Kechirasiz, faqat *{stock}* dona qoldi.',
    addedToCart: '✅ *{name}* ({qty} dona) savatga qo\'shildi!\n\n🛒 Savatda: *{count} ta mahsulot*\n💰 Jami: *{total}*',
    continue: '🛍️ Davom etish',
    confirmOrder: '✅ Buyurtmani tasdiqlash',
    cartEmpty: '🛒 *Savatingiz bo\'sh*\n\nMahsulot tanlash uchun "Mahsulotlar" tugmasini bosing.',
    cart: '🛒 *Savatingiz:*\n\n{items}\n💰 *Jami: {total}*\n📦 *Mahsulotlar: {count} ta*',
    cartItem: '{i}. *{name}*\n   {qty} x {price} = *{subtotal}*\n\n',
    remove: '🗑️ {name} ({qty} dona)',
    clearCart: '🗑️ Savatni tozalash',
    cartCleared: '🗑️ Savat tozalandi.',
    orderSummary: '🧾 *Buyurtma xulosasi:*\n\n{items}\n💰 *Jami: {total}*',
    orderItem: '{i}. {name}\n   {qty} x {price} = *{subtotal}*\n\n',
    customer: '👤 Buyurtmachi: *{name}*',
    confirm: '✅ Tasdiqlaysizmi?',
    askDelivery: '🚚 *Yetkazib berish kerakmi?',
    deliveryYes: '✅ Ha, yetkazib berilsin',
    deliveryNo: '❌ Yo\'q, o\'zim olib ketaman',
    deliveryAddress: '📍 *Yetkazib berish manzili*\n\nIltimos, manzilingizni yozing (masalan: Chilonzor 9-mavze, 12-uy) yoki lokatsiya yuboring:',
    sendLocation: '📍 Lokatsiya yuborish',
    locationPrompt: '📍 *Lokatsiya yuboring*\n\nTelegramdagi 📎 → Joylashuv orqali lokatsiyangizni yuboring:',
    pickup: '\n🏪 *Do\'kondan olib ketish*\n',
    deliveryText: '\n🚚 *Yetkazib berish:* {address}\n',
    orderSuccess: '✅ *Buyurtma muvaffaqiyatli qabul qilindi!*\n\n{items}\n{delivery}\n📋 Chek: `{invoice}`\n\n📞 Bog\'lanish: @{admin}\n\nRahmat! Yana xizmatingizdamiz! 🙏',
    newOrder: '🔔 *YANGI BUYURTMA!*\n\n{items}\n👤 Buyurtmachi: *{customer}*\n🆔 Chat ID: `{chatId}`\n📋 Chek: `{invoice}`\n{delivery}⏰ Vaqt: {time}\n',
    orderError: '❌ Buyurtma berishda xatolik yuz berdi. Iltimos, qayta urinib ko\'ring.',
    newOrderBtn: '🛍️ Yangi buyurtma',
    searchPrompt: '🔍 *Mahsulot qidirish*\n\nMahsulot nomini yozing:',
    enterNumber: '❌ Iltimos, son kiriting (masalan: 3)',
    adminOnly: '❌ Sizda bu buyruqni bajarish huquqi yo\'q.',
    noOrders: '📋 Hozircha buyurtmalar yo\'q.',
    ordersList: '📋 *Oxirgi buyurtmalar:*\n\n',
    orderItem_short: '{i}. `{invoice}`\n   👤 {customer}\n   💰 {amount}\n   📅 {date}\n\n',
    noDeliveries: '🚚 Hozircha yetkazib berish kerak bo\'lgan buyurtmalar yo\'q.',
    deliveriesList: '🚚 *Yetkazib berish kerak bo\'lgan buyurtmalar:*\n\n',
    deliveryItem: '{i}. `{invoice}`\n   👤 {customer}\n   💰 {amount}\n   📍 {address}\n   📅 {date}\n\n',
    help: '📚 *Yordam*\n\n/start - Botni ishga tushirish\n/products - Mahsulotlar ro\'yxati\n/cart - Savatimni ko\'rish\n/myorders - Mening buyurtmalarim\n/orders - Oxirgi buyurtmalar (faqat admin)\n/delivery - Yetkazib berishlar (faqat admin)\n/lang - Tilni o\'zgartirish\n/help - Bu yordam\n\n🛒 Bot orqali mahsulotlarni ko\'rishingiz va buyurtma qilishingiz mumkin.\n🚚 Yetkazib berish xizmati mavjud!\n\n📞 Admin: @{admin}',
    langChanged: '✅ Til o\'zgartirildi: {lang}',
    errorOccurred: '❌ Xatolik yuz berdi.',
    myOrders_title: '📋 *Mening buyurtmalarim*',
    noOrdersUser: 'Sizning buyurtmalaringiz yo\'q.',
    stockCheck: '📊 *Zaxira holati:*\n\n✅ Mavjud: *{available}* ta\n⚠️ Kam qoldi: *{low}* ta\n❌ Tugagan: *{out}* ta',
    stockOut: '❌ *Tugagan mahsulotlar:*\n',
    stockLow: '⚠️ *Kam qolgan mahsulotlar:*\n',
    stockItem: '  • {name} ({stock} qoldi)\n',
    stockOutItem: '  • {name}\n',
    productsList: '📋 *{title}* ({count} ta)\n\n{list}\n\nMahsulotni tanlang:',
    selectCategory: '📂 *Kategoriyalar:*\n\nQaysi kategoriyadan mahsulot ko\'rmoqchisiz?',
  },

  ru: {
    name: 'Русский',
    flag: '🇷🇺',
    start: 'Здравствуйте, *{name}*! 👋\n\n🍽️ *Добро пожаловать в продуктовый магазин!*\n\nЯ могу рассказать вам о товарах и помочь сделать заказ.',
    chooseLang: '🌐 *Выберите язык:*',
    mainMenu: '📌 Что хотите сделать?',
    products: '🛍️ Товары',
    search: '🔍 Поиск',
    myCart: '🛒 Корзина',
    myOrders: '📋 Мои заказы',
    back: '⬅️ Назад',
    backMain: '⬅️ Главная',
    noProducts: 'Пока товаров нет. 😔',
    categories: '📂 *Категории:*\n\nКакую категорию хотите посмотреть?',
    categoryProducts: 'Товары категории',
    allProducts: 'Все товары',
    noProductsCat: 'В этой категории товаров нет. 😔',
    productDetail: '📦 *{name}*\n\n{image}{brand}📂 Категория: {category}\n💰 Цена: *{price}*\n📏 Ед. изм.: {unit}\n📦 Остаток: *{stock} шт* {status}\n{description}',
    brand: '🏷️ Бренд: {brand}\n',
    imageLink: '🖼️ Фото: [Смотреть]({url})\n',
    inStock: '✅ В наличии',
    lowStock: '⚠️ Мало',
    outOfStock: '❌ Нет в наличии',
    addToCart: '🛒 Добавить в корзину',
    viewCart: '📋 Моя корзина',
    notFound: 'Товар не найден',
    notFoundSearch: '🔍 По запросу "{query}" ничего не найдено.',
    foundSearch: '🔍 По запросу "{query}" найдено *{count}* товаров:',
    addToCartQty: '🛒 Добавляем *{name}* в корзину\n\n💰 Цена: *{price}*\n📦 В наличии: *{stock} шт*\n\nСколько нужно?\n💡 *Нажмите число или введите сами (например: 5)*',
    cancel: '❌ Отмена',
    error: '❌ Произошла ошибка',
    onlyStock: '❌ Извините, осталось только *{stock}* шт.',
    addedToCart: '✅ *{name}* ({qty} шт) добавлено в корзину!\n\n🛒 В корзине: *{count} товаров*\n💰 Сумма: *{total}*',
    continue: '🛍️ Продолжить',
    confirmOrder: '✅ Подтвердить заказ',
    cartEmpty: '🛒 *Корзина пуста*\n\nНажмите "Товары", чтобы выбрать продукты.',
    cart: '🛒 *Корзина:*\n\n{items}\n💰 *Сумма: {total}*\n📦 *Товаров: {count} шт*',
    cartItem: '{i}. *{name}*\n   {qty} x {price} = *{subtotal}*\n\n',
    remove: '🗑️ {name} ({qty} шт)',
    clearCart: '🗑️ Очистить корзину',
    cartCleared: '🗑️ Корзина очищена.',
    orderSummary: '🧾 *Итого заказа:*\n\n{items}\n💰 *Сумма: {total}*',
    orderItem: '{i}. {name}\n   {qty} x {price} = *{subtotal}*\n\n',
    customer: '👤 Заказчик: *{name}*',
    confirm: '✅ Подтверждаете?',
    askDelivery: '🚚 *Нужна доставка?',
    deliveryYes: '✅ Да, доставить',
    deliveryNo: '❌ Нет, заберу сам',
    deliveryAddress: '📍 *Адрес доставки*\n\nНапишите ваш адрес (например: Чиланзар 9-квартал, д.12) или отправьте локацию:',
    sendLocation: '📍 Отправить локацию',
    locationPrompt: '📍 *Отправьте локацию*\n\nНажмите 📎 → Локация в Telegram и отправьте:',
    pickup: '\n🏪 *Самовывоз из магазина*\n',
    deliveryText: '\n🚚 *Доставка:* {address}\n',
    orderSuccess: '✅ *Заказ успешно принят!*\n\n{items}\n{delivery}\n📋 Чек: `{invoice}`\n\n📞 Контакт: @{admin}\n\nСпасибо! Ждем вас снова! 🙏',
    newOrder: '🔔 *НОВЫЙ ЗАКАЗ!*\n\n{items}\n👤 Заказчик: *{customer}*\n🆔 Chat ID: `{chatId}`\n📋 Чек: `{invoice}`\n{delivery}⏰ Время: {time}\n',
    orderError: '❌ Ошибка при оформлении заказа. Попробуйте снова.',
    newOrderBtn: '🛍️ Новый заказ',
    searchPrompt: '🔍 *Поиск товаров*\n\nВведите название товара:',
    enterNumber: '❌ Пожалуйста, введите число (например: 3)',
    adminOnly: '❌ У вас нет прав для этой команды.',
    noOrders: '📋 Заказов пока нет.',
    ordersList: '📋 *Последние заказы:*\n\n',
    orderItem_short: '{i}. `{invoice}`\n   👤 {customer}\n   💰 {amount}\n   📅 {date}\n\n',
    noDeliveries: '🚚 Заказов на доставку пока нет.',
    deliveriesList: '🚚 *Заказы на доставку:*\n\n',
    deliveryItem: '{i}. `{invoice}`\n   👤 {customer}\n   💰 {amount}\n   📍 {address}\n   📅 {date}\n\n',
    help: '📚 *Помощь*\n\n/start - Запустить бота\n/products - Список товаров\n/cart - Моя корзина\n/myorders - Мои заказы\n/orders - Последние заказы (только админ)\n/delivery - Доставки (только админ)\n/lang - Сменить язык\n/help - Эта помощь\n\n🛒 Через бота можно смотреть товары и делать заказы.\n🚚 Есть доставка!\n\n📞 Админ: @{admin}',
    langChanged: '✅ Язык изменен: {lang}',
    errorOccurred: '❌ Произошла ошибка.',
    myOrders_title: '📋 *Мои заказы*',
    noOrdersUser: 'У вас нет заказов.',
    stockCheck: '📊 *Состояние склада:*\n\n✅ В наличии: *{available}* шт\n⚠️ Мало: *{low}* шт\n❌ Нет в наличии: *{out}* шт',
    stockOut: '❌ *Нет в наличии:*\n',
    stockLow: '⚠️ *Мало на складе:*\n',
    stockItem: '  • {name} (осталось {stock})\n',
    stockOutItem: '  • {name}\n',
    productsList: '📋 *{title}* ({count} шт)\n\n{list}\n\nВыберите товар:',
    selectCategory: '📂 *Категории:*\n\nКакую категорию хотите посмотреть?',
  },
};

function t(lang, key, vars = {}) {
  let str = (LANG[lang] || LANG.uz)[key] || key;
  for (const [k, v] of Object.entries(vars)) {
    str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
  }
  return str;
}

module.exports = { t, LANG };
