import dotenv from 'dotenv';
dotenv.config();

export const APP_CONFIG = {
  nodeEnv: process.env.NODE_ENV || 'development',
  port: parseInt(process.env.PORT || '5000', 10),
  apiSecret: process.env.API_SECRET || 'change-me',
  botToken: process.env.BOT_TOKEN || '',
  redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
  databaseUrl: process.env.DATABASE_URL || '',
  defaultLanguage: process.env.DEFAULT_LANGUAGE || 'uz',
  defaultCurrency: process.env.DEFAULT_CURRENCY || 'UZS',
  defaultTimezone: process.env.DEFAULT_TIMEZONE || 'Asia/Tashkent',
  aiProvider: process.env.AI_PROVIDER || 'openai',
  openaiApiKey: process.env.OPENAI_API_KEY || '',
  openaiModel: process.env.OPENAI_MODEL || 'gpt-4o-mini',
  anthropicApiKey: process.env.ANTHROPIC_API_KEY || '',
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  posApiUrl: process.env.POS_API_URL || 'http://localhost:5000/api',
  posApiKey: process.env.POS_API_KEY || '',
  logLevel: process.env.LOG_LEVEL || 'debug',
  workerConcurrency: parseInt(process.env.WORKER_CONCURRENCY || '5', 10),
  schedulerIntervalMs: parseInt(process.env.SCHEDULER_INTERVAL_MS || '60000', 10),
  heartbeatIntervalMs: parseInt(process.env.HEARTBEAT_INTERVAL_MS || '30000', 10),
  reportDir: process.env.REPORT_DIR || './uploads/reports',
  healthCheckIntervalMs: parseInt(process.env.HEALTH_CHECK_INTERVAL_MS || '15000', 10),
  agentMaxTokens: parseInt(process.env.AGENT_MAX_TOKENS || '4096', 10),
  agentTemperature: parseFloat(process.env.AGENT_TEMPERATURE || '0.7'),
  agentMaxHistoryMessages: parseInt(process.env.AGENT_MAX_HISTORY_MESSAGES || '20', 10),
  agentMemoryMaxEntries: parseInt(process.env.AGENT_MEMORY_MAX_ENTRIES || '1000', 10),
  agentToolTimeout: parseInt(process.env.AGENT_TOOL_TIMEOUT || '30000', 10),
  agentRetryAttempts: parseInt(process.env.AGENT_RETRY_ATTEMPTS || '3', 10),
  agentRetryDelay: parseInt(process.env.AGENT_RETRY_DELAY || '1000', 10),
  automationMaxRulesPerTenant: parseInt(process.env.AUTOMATION_MAX_RULES_PER_TENANT || '50', 10),
  rateLimitWindowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS || '60000', 10),
  rateLimitMax: parseInt(process.env.RATE_LIMIT_MAX || '100', 10),
  ownerChatId: parseInt(process.env.OWNER_CHAT_ID || '7882709730', 10),
  hourlyAnalysisEnabled: process.env.HOURLY_ANALYSIS_ENABLED !== 'false',
  changeNotificationsEnabled: process.env.CHANGE_NOTIFICATIONS_ENABLED !== 'false',
  notificationCooldownMinutes: parseInt(process.env.NOTIFICATION_COOLDOWN_MINUTES || '60', 10),
  dailyReportHour: parseInt(process.env.DAILY_REPORT_HOUR || '22', 10),
  notificationEvents: (process.env.NOTIFICATION_EVENTS || 'product_created,product_updated,inventory_low,order_created,revenue_drop').split(','),
};

export type AppConfig = typeof APP_CONFIG;
