export const translations = {
  uz: {
    // Common
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    delete: "O'chirish",
    edit: "Tahrirlash",
    add: "Qo'shish",
    search: 'Qidirish...',
    loading: 'Yuklanmoqda...',
    noData: "Ma'lumot topilmadi",
    confirm: 'Tasdiqlash',
    actions: 'Amallar',
    total: 'Jami',
    status: 'Holat',
    active: 'Faol',
    inactive: 'Nofaol',
    all: 'Barchasi',
    close: 'Yopish',
    print: 'Chop etish',
    export: 'Eksport',
    filter: 'Filtrlash',
    back: 'Orqaga',
    yes: 'Ha',
    no: "Yo'q",
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    login: 'Kirish',
    logout: 'Chiqish',
    email: 'Elektron pochta',
    password: 'Parol',
    rememberMe: 'Eslab qolish',
    signIn: 'Tizimga kirish',
    signUp: "Ro'yxatdan o'tish",
    fullName: 'Ism Familiya',
    creating: 'Yaratilmoqda...',
    signingIn: 'Kirilmoqda...',
    welcomeBack: 'Xush kelibsiz!',
    loginSubtitle: 'POS tizimiga kiring',
    demoCredentials: 'Demo: admin@pos.uz / password',
    // Dashboard
    dashboard: 'Boshqaruv paneli',
    pos: 'Kassa',
    products: 'Mahsulotlar',
    sales: 'Sotuvlar',
    reports: 'Hisobotlar',
    settings: 'Sozlamalar',
    profile: 'Profil',
    inventory: 'Ombor',
    dashboardTitle: 'Boshqaruv paneli',
    dashboardSubtitle: "Xush kelibsiz! Biznesingiz haqida umumiy ma'lumot.",
    todayRevenue: 'Bugungi tushum',
    monthlyRevenue: 'Oylik tushum',
    totalProducts: 'Jami mahsulotlar',
    lowStock: 'Kam qoldi',
    transactions: 'tranzaksiya',
    inventoryValue: 'ombor qiymati',
    outOfStock: 'Tugadi',
    recentSales: 'Oxirgi sotuvlar',
    topProducts: 'TOP mahsulotlar',
    noSalesToday: 'Bugun sotuv yo\'q',
    weeklySales: 'Haftalik sotuvlar',
    // Products
    productsTitle: 'Mahsulotlar',
    addProduct: "Mahsulot qo'shish",
    editProduct: 'Mahsulotni tahrirlash',
    productName: 'Mahsulot nomi',
    productCode: 'Kod',
    barcode: 'Shtrix-kod',
    category: 'Kategoriya',
    brand: 'Brend',
    purchasePrice: 'Xarid narxi',
    sellingPrice: 'Sotish narxi',
    stockQuantity: 'Mavjud miqdor',
    minimumStock: 'Minimal zaxira',
    unit: "O'lchov birligi",
    description: 'Tavsif',
    noCategory: "Kategoriya yo'q",
    allCategories: 'Barcha kategoriyalar',
    labels: 'Yorliqlar',
    deleteProduct: "Mahsulotni o'chirish",
    deleteConfirm: "haqiqatan ham o'chirishni xohlaysizmi?",
    outOfStockStatus: 'Tugadi',
    lowStockStatus: 'Kam qoldi',
    inStockStatus: 'Mavjud',
    // Cart
    cart: 'Savat',
    clear: 'Tozalash',
    emptyCart: 'Savat bo\'sh',
    emptyCartHint: 'Mahsulot qidirib yoki skanerlang',
    scan: 'Skanerlash',
    searchOrScan: 'Qidirish yoki skanerlash...',
    each: 'dona',
    items: 'Mahsulotlar',
    proceedCheckout: "To'lovga o'tish",
    checkout: "To'lov",
    totalAmount: 'Jami summa',
    customerName: 'Mijoz nomi',
    walkInCustomer: "O'tib ketayotgan mijoz",
    paymentMethod: "To'lov usuli",
    cash: 'Naqd',
    card: 'Karta',
    other: 'Boshqa',
    receivedAmount: 'Qabul qilingan summa',
    change: 'Qaytim',
    completeSale: "Sotuvni yakunlash",
    processing: 'Qayta ishlanmoqda...',
    saleComplete: 'Sotuv tugallandi!',
    paymentSuccessful: "To'lov muvaffaqiyatli!",
    printReceipt: "Chekni chop etish",
    scanBarcode: "Shtrix-kodni skanerlash",
    pointCamera: "Kamerani shtrix-kodga yo'naltiring...",
    cameraError: "Kamera mavjud emas. Shtrix-kodni qo'lda kiriting.",
    notFound: 'Mahsulot topilmadi',
    notEnoughStock: 'Yetarli zaxira yo\'q',
    productAdded: "qo'shildi",
    insufficientStock: 'Zaxira yetarli emas',
    // Sales
    salesTitle: 'Sotuvlar tarixi',
    invoice: 'Hisob-faktura',
    customer: 'Mijoz',
    cashier: 'Kassir',
    amount: 'Summa',
    date: 'Sana',
    time: 'Vaqt',
    payment: "To'lov",
    view: "Ko'rish",
    fromDate: 'Dan',
    toDate: 'Gacha',
    allMethods: 'Barcha usullar',
    // Reports
    reportsTitle: 'Hisobotlar',
    analytics: "Tahlillar va ma'lumotlar",
    dailySales: 'Kunlik sotuvlar',
    monthlySales: 'Oylik sotuvlar',
    topSelling: 'TOP sotilganlar',
    inventoryReport: "Ombor hisoboti",
    totalSalesCount: 'Jami sotuvlar',
    totalRevenue: 'Jami tushum',
    paymentMethods: "To'lov usullari",
    salesList: 'Sotuvlar ro\'yxati',
    dailyRevenue: 'Kunlik tushum',
    monthlySummary: 'Oylik xulosa',
    topSellingProducts: "Eng ko'p sotilgan mahsulotlar",
    totalProductsReport: 'Jami mahsulotlar',
    stockValue: 'Zaxira qiymati',
    lowStockCount: 'Kam qoldi',
    outOfStockCount: 'Tugadi',
    inventoryList: 'Ombor ro\'yxati',
    // Settings
    settingsTitle: 'Sozlamalar',
    storeInfo: "Do'kon ma'lumotlari",
    storeName: "Do'kon nomi",
    phone: 'Telefon',
    address: 'Manzil',
    currencyTax: 'Valyuta va soliq',
    currency: 'Valyuta',
    symbol: 'Belgi',
    taxPercent: 'Soliq %',
    receiptSettings: 'Chek sozlamalari',
    receiptHeader: 'Chek yuqorisi',
    receiptFooter: 'Chek pasti',
    lowStockThreshold: 'Kam zaxira chegarasi',
    saveSettings: 'Sozlamalarni saqlash',
    settingsSaved: 'Sozlamalar saqlandi!',
    // Profile
    profileTitle: 'Profil',
    name: 'Ism',
    role: 'Rol',
    admin: 'Admin',
    cashier_role: 'Kassir',
    memberSince: "A'zo bo'lgan sana",
    notifications: 'Bildirishnomalar',
    noNotifications: "Bildirishnoma yo'q",
    lowStockAlert: 'Kam zaxira ogohlantirishi',
    productRunningLow: 'mahsulot kam qoldi',
    markAllRead: "Barchasini o'qilgan deb belgilash",
    daily: 'Kunlik',
    weekly: 'Haftalik',
    monthly: 'Oylik',
    receipt: 'Chek',
    subtotal: 'Oraliq yig\'indisi',
    tax: 'Soliq',
    pcs: 'dona',
    kg: 'kg',
    g: 'gram',
    l: 'litr',
    ml: 'ml',
    box: 'quti',
    bag: 'xalta',
    bottle: 'butulka',
    jar: 'idish',
    pack: 'payket',
    soom: "so'm",
    // Sidebar
    main: 'Asosiy',
    productsGroup: 'Mahsulotlar',
    trade: 'Savdo',
    management: 'Boshqaruv',
    dashboardNav: 'Dashboard',
    posNav: 'Kassa',
    productsNav: 'Mahsulotlar',
    categoriesNav: 'Kategoriyalar',
    salesNav: 'Sotuvlar',
    reportsNav: 'Hisobotlar',
    debtorsNav: 'Qarzdorlar',
    suppliersNav: 'Yetkazib beruvchilar',
    discountsNav: 'Chegirmalar',
    settingsNav: 'Sozlamalar',
    // Debtors
    debtorsTitle: 'Qarzdorlar',
    addDebtor: "Qarzdor qo'shish",
    debtorName: 'Ism familiya',
    debtAmount: 'Qarz miqdori',
    totalDebt: 'Jami qarz',
    night: 'Tun',
    day: 'Kun',
    // Header
    toggleSidebar: 'Sidebarni ochish/yopish',
    changeLang: "Tilni o'zgartirish",
    hideAll: 'Barchasini yashirish',
    hide: 'Yashirish',
    remaining: 'qoldi',
    // Sidebar
    posSystem: 'POS System',
    user: 'Foydalanuvchi',
    admin: 'Admin',
    cashier_role: 'Kassir',
  },
  ru: {
    // Common
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Редактировать',
    add: 'Добавить',
    search: 'Поиск...',
    loading: 'Загрузка...',
    noData: 'Данные не найдены',
    confirm: 'Подтвердить',
    actions: 'Действия',
    total: 'Итого',
    status: 'Статус',
    active: 'Активный',
    inactive: 'Неактивный',
    all: 'Все',
    close: 'Закрыть',
    print: 'Печать',
    export: 'Экспорт',
    filter: 'Фильтр',
    back: 'Назад',
    yes: 'Да',
    no: 'Нет',
    confirmDelete: 'Вы уверены, что хотите удалить?',
    login: 'Вход',
    logout: 'Выход',
    email: 'Электронная почта',
    password: 'Пароль',
    rememberMe: 'Запомнить',
    signIn: 'Войти',
    signUp: 'Регистрация',
    fullName: 'Имя Фамилия',
    creating: 'Создание...',
    signingIn: 'Вход...',
    welcomeBack: 'Добро пожаловать!',
    loginSubtitle: 'Войдите в POS систему',
    demoCredentials: 'Демо: admin@pos.uz / password',
    // Dashboard
    dashboard: 'Панель управления',
    pos: 'Касса',
    products: 'Товары',
    sales: 'Продажи',
    reports: 'Отчёты',
    settings: 'Настройки',
    profile: 'Профиль',
    inventory: 'Склад',
    dashboardTitle: 'Панель управления',
    dashboardSubtitle: 'Добро пожаловать! Обзор вашего бизнеса.',
    todayRevenue: 'Сегодняшний доход',
    monthlyRevenue: 'Месячный доход',
    totalProducts: 'Всего товаров',
    lowStock: 'Мало на складе',
    transactions: 'транзакций',
    inventoryValue: 'стоимость склада',
    outOfStock: 'Нет в наличии',
    recentSales: 'Последние продажи',
    topProducts: 'Топ товары',
    noSalesToday: 'Сегодня продаж нет',
    weeklySales: 'Недельные продажи',
    // Products
    productsTitle: 'Товары',
    addProduct: 'Добавить товар',
    editProduct: 'Редактировать товар',
    productName: 'Название товара',
    productCode: 'Код',
    barcode: 'Штрих-код',
    category: 'Категория',
    brand: 'Бренд',
    purchasePrice: 'Закупочная цена',
    sellingPrice: 'Цена продажи',
    stockQuantity: 'Количество',
    minimumStock: 'Минимальный запас',
    unit: 'Единица измерения',
    description: 'Описание',
    noCategory: 'Нет категории',
    allCategories: 'Все категории',
    labels: 'Этикетки',
    deleteProduct: 'Удалить товар',
    deleteConfirm: 'Вы действительно хотите удалить?',
    outOfStockStatus: 'Нет в наличии',
    lowStockStatus: 'Мало',
    inStockStatus: 'В наличии',
    // Cart
    cart: 'Корзина',
    clear: 'Очистить',
    emptyCart: 'Корзина пуста',
    emptyCartHint: 'Найдите или отсканируйте товар',
    scan: 'Сканер',
    searchOrScan: 'Поиск или сканирование...',
    each: 'шт',
    items: 'Товары',
    proceedCheckout: 'Перейти к оплате',
    checkout: 'Оплата',
    totalAmount: 'Итого',
    customerName: 'Имя клиента',
    walkInCustomer: 'Прохожий клиент',
    paymentMethod: 'Способ оплаты',
    cash: 'Наличные',
    card: 'Карта',
    other: 'Другое',
    receivedAmount: 'Получено',
    change: 'Сдача',
    completeSale: 'Завершить продажу',
    processing: 'Обработка...',
    saleComplete: 'Продажа завершена!',
    paymentSuccessful: 'Оплата прошла успешно!',
    printReceipt: 'Печать чека',
    scanBarcode: 'Сканировать штрих-код',
    pointCamera: 'Направьте камеру на штрих-код...',
    cameraError: 'Камера недоступна. Введите штрих-код вручную.',
    notFound: 'Товар не найден',
    notEnoughStock: 'Недостаточно товара',
    productAdded: 'добавлен',
    insufficientStock: 'Недостаточно на складе',
    // Sales
    salesTitle: 'История продаж',
    invoice: 'Номер чека',
    customer: 'Клиент',
    cashier: 'Кассир',
    amount: 'Сумма',
    date: 'Дата',
    time: 'Время',
    payment: 'Оплата',
    view: 'Просмотр',
    fromDate: 'С',
    toDate: 'По',
    allMethods: 'Все способы',
    // Reports
    reportsTitle: 'Отчёты',
    analytics: 'Аналитика и данные',
    dailySales: 'Дневные продажи',
    monthlySales: 'Месячные продажи',
    topSelling: 'Топ продаж',
    inventoryReport: 'Отчёт по складу',
    totalSalesCount: 'Всего продаж',
    totalRevenue: 'Общий доход',
    paymentMethods: 'Способы оплаты',
    salesList: 'Список продаж',
    dailyRevenue: 'Дневной доход',
    monthlySummary: 'Месячный итог',
    topSellingProducts: 'Самые продаваемые товары',
    totalProductsReport: 'Всего товаров',
    stockValue: 'Стоимость склада',
    lowStockCount: 'Мало на складе',
    outOfStockCount: 'Нет в наличии',
    inventoryList: 'Список склада',
    // Settings
    settingsTitle: 'Настройки',
    storeInfo: 'Информация о магазине',
    storeName: 'Название магазина',
    phone: 'Телефон',
    address: 'Адрес',
    currencyTax: 'Валюта и налог',
    currency: 'Валюта',
    symbol: 'Символ',
    taxPercent: 'Налог %',
    receiptSettings: 'Настройки чека',
    receiptHeader: 'Шапка чека',
    receiptFooter: 'Подвал чека',
    lowStockThreshold: 'Порог малого запаса',
    saveSettings: 'Сохранить настройки',
    settingsSaved: 'Настройки сохранены!',
    // Profile
    profileTitle: 'Профиль',
    name: 'Имя',
    role: 'Роль',
    admin: 'Админ',
    cashier_role: 'Кассир',
    memberSince: 'Участник с',
    notifications: 'Уведомления',
    noNotifications: 'Нет уведомлений',
    lowStockAlert: 'О малоом запасе',
    productRunningLow: 'товар заканчивается',
    markAllRead: 'Отметить все как прочитанные',
    daily: 'Дневной',
    weekly: 'Недельный',
    monthly: 'Месячный',
    receipt: 'Чек',
    subtotal: 'Промежуточный итог',
    tax: 'Налог',
    pcs: 'шт',
    kg: 'кг',
    g: 'грамм',
    l: 'литр',
    ml: 'мл',
    box: 'коробка',
    bag: 'мешок',
    bottle: 'бутылка',
    jar: 'банка',
    pack: 'упаковка',
    soom: 'сум',
    // Sidebar
    main: 'Основное',
    productsGroup: 'Товары',
    trade: 'Торговля',
    management: 'Управление',
    dashboardNav: 'Панель',
    posNav: 'Касса',
    productsNav: 'Товары',
    categoriesNav: 'Категории',
    salesNav: 'Продажи',
    reportsNav: 'Отчёты',
    debtorsNav: 'Должники',
    suppliersNav: 'Поставщики',
    discountsNav: 'Скидки',
    settingsNav: 'Настройки',
    // Debtors
    debtorsTitle: 'Должники',
    addDebtor: 'Добавить должника',
    debtorName: 'ФИО',
    debtAmount: 'Сумма долга',
    totalDebt: 'Общий долг',
    night: 'Ночь',
    day: 'День',
    // Header
    toggleSidebar: 'Открыть/закрыть боковую панель',
    changeLang: 'Изменить язык',
    hideAll: 'Скрыть все',
    hide: 'Скрыть',
    remaining: 'осталось',
    // Sidebar
    posSystem: 'POS System',
    user: 'Пользователь',
    admin: 'Администратор',
    cashier_role: 'Кассир',
  },
  en: {
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search...',
    loading: 'Loading...',
    noData: 'No data found',
    confirm: 'Confirm',
    actions: 'Actions',
    total: 'Total',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    close: 'Close',
    print: 'Print',
    export: 'Export',
    filter: 'Filter',
    back: 'Back',
    yes: 'Yes',
    no: 'No',
    confirmDelete: 'Are you sure you want to delete?',
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    signIn: 'Sign in',
    signUp: 'Create account',
    fullName: 'Full name',
    creating: 'Creating...',
    signingIn: 'Signing in...',
    welcomeBack: 'Welcome back!',
    loginSubtitle: 'Sign in to POS system',
    demoCredentials: 'Demo: admin@pos.uz / password',
    // Dashboard
    dashboard: 'Dashboard',
    pos: 'POS',
    products: 'Products',
    sales: 'Sales',
    reports: 'Reports',
    settings: 'Settings',
    profile: 'Profile',
    inventory: 'Inventory',
    dashboardTitle: 'Dashboard',
    dashboardSubtitle: 'Welcome! Overview of your business.',
    todayRevenue: "Today's Revenue",
    monthlyRevenue: 'Monthly Revenue',
    totalProducts: 'Total Products',
    lowStock: 'Low Stock',
    transactions: 'transactions',
    inventoryValue: 'inventory value',
    outOfStock: 'Out of Stock',
    recentSales: 'Recent Sales',
    topProducts: 'Top Products',
    noSalesToday: 'No sales today',
    weeklySales: 'Weekly Sales',
    // Products
    productsTitle: 'Products',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    productName: 'Product Name',
    productCode: 'Code',
    barcode: 'Barcode',
    category: 'Category',
    brand: 'Brand',
    purchasePrice: 'Purchase Price',
    sellingPrice: 'Selling Price',
    stockQuantity: 'Stock Quantity',
    minimumStock: 'Minimum Stock',
    unit: 'Unit',
    description: 'Description',
    noCategory: 'No category',
    allCategories: 'All Categories',
    labels: 'Labels',
    deleteProduct: 'Delete Product',
    deleteConfirm: 'Are you sure you want to delete?',
    outOfStockStatus: 'Out of Stock',
    lowStockStatus: 'Low Stock',
    inStockStatus: 'In Stock',
    // Cart
    cart: 'Cart',
    clear: 'Clear',
    emptyCart: 'Cart is empty',
    emptyCartHint: 'Search or scan products',
    scan: 'Scan',
    searchOrScan: 'Search or scan...',
    each: 'ea',
    items: 'Items',
    proceedCheckout: 'Proceed to Checkout',
    checkout: 'Checkout',
    totalAmount: 'Total Amount',
    customerName: 'Customer Name',
    walkInCustomer: 'Walk-in Customer',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    other: 'Other',
    receivedAmount: 'Received Amount',
    change: 'Change',
    completeSale: 'Complete Sale',
    processing: 'Processing...',
    saleComplete: 'Sale Complete!',
    paymentSuccessful: 'Payment Successful!',
    printReceipt: 'Print Receipt',
    scanBarcode: 'Scan Barcode',
    pointCamera: 'Point camera at barcode...',
    cameraError: 'Camera not available. Enter barcode manually.',
    notFound: 'Product not found',
    notEnoughStock: 'Not enough stock',
    productAdded: 'added',
    insufficientStock: 'Insufficient stock',
    // Sales
    salesTitle: 'Sales History',
    invoice: 'Invoice',
    customer: 'Customer',
    cashier: 'Cashier',
    amount: 'Amount',
    date: 'Date',
    time: 'Time',
    payment: 'Payment',
    view: 'View',
    fromDate: 'From',
    toDate: 'To',
    allMethods: 'All Methods',
    // Reports
    reportsTitle: 'Reports',
    analytics: 'Analytics & Data',
    dailySales: 'Daily Sales',
    monthlySales: 'Monthly Sales',
    topSelling: 'Top Selling',
    inventoryReport: 'Inventory Report',
    totalSalesCount: 'Total Sales',
    totalRevenue: 'Total Revenue',
    paymentMethods: 'Payment Methods',
    salesList: 'Sales List',
    dailyRevenue: 'Daily Revenue',
    monthlySummary: 'Monthly Summary',
    topSellingProducts: 'Top Selling Products',
    totalProductsReport: 'Total Products',
    stockValue: 'Stock Value',
    lowStockCount: 'Low Stock',
    outOfStockCount: 'Out of Stock',
    inventoryList: 'Inventory List',
    // Settings
    settingsTitle: 'Settings',
    storeInfo: 'Store Information',
    storeName: 'Store Name',
    phone: 'Phone',
    address: 'Address',
    currencyTax: 'Currency & Tax',
    currency: 'Currency',
    symbol: 'Symbol',
    taxPercent: 'Tax %',
    receiptSettings: 'Receipt Settings',
    receiptHeader: 'Receipt Header',
    receiptFooter: 'Receipt Footer',
    lowStockThreshold: 'Low Stock Threshold',
    saveSettings: 'Save Settings',
    settingsSaved: 'Settings saved!',
    // Profile
    profileTitle: 'Profile',
    name: 'Name',
    role: 'Role',
    admin: 'Admin',
    cashier_role: 'Cashier',
    memberSince: 'Member Since',
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    lowStockAlert: 'Low Stock Alert',
    productRunningLow: 'product is running low',
    markAllRead: 'Mark all as read',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    receipt: 'Receipt',
    subtotal: 'Subtotal',
    tax: 'Tax',
    pcs: 'pcs',
    kg: 'kg',
    g: 'g',
    l: 'L',
    ml: 'ml',
    box: 'box',
    bag: 'bag',
    bottle: 'bottle',
    jar: 'jar',
    pack: 'pack',
    soom: 'UZS',
    // Sidebar
    main: 'Main',
    productsGroup: 'Products',
    trade: 'Trade',
    management: 'Management',
    dashboardNav: 'Dashboard',
    posNav: 'POS',
    productsNav: 'Products',
    categoriesNav: 'Categories',
    salesNav: 'Sales',
    reportsNav: 'Reports',
    debtorsNav: 'Debtors',
    suppliersNav: 'Suppliers',
    discountsNav: 'Discounts',
    settingsNav: 'Settings',
    // Debtors
    debtorsTitle: 'Debtors',
    addDebtor: 'Add Debtor',
    debtorName: 'Full Name',
    debtAmount: 'Debt Amount',
    totalDebt: 'Total Debt',
    night: 'Night',
    day: 'Day',
    // Header
    toggleSidebar: 'Toggle sidebar',
    changeLang: 'Change language',
    hideAll: 'Hide all',
    hide: 'Hide',
    remaining: 'remaining',
    // Sidebar
    posSystem: 'POS System',
    user: 'User',
    admin: 'Admin',
    cashier_role: 'Cashier',
  },
};

// Default to Uzbek
let currentLang = localStorage.getItem('pos_lang') || 'uz';

export const setLanguage = (lang) => {
  currentLang = lang;
  localStorage.setItem('pos_lang', lang);
};

export const getLanguage = () => currentLang;

// Get translation for a key
export const t = (key) => {
  return translations[currentLang]?.[key] || translations.uz[key] || key;
};

// Legacy UZ object (uses current language)
export const UZ = new Proxy({}, {
  get(target, prop) {
    return translations[currentLang]?.[prop] || translations.uz[prop] || prop;
  }
});

export const formatCurrency = (amount) => {
  const num = Number(amount || 0);
  if (currentLang === 'en') return `$${num.toLocaleString('en-US')}`;
  if (currentLang === 'ru') return `${num.toLocaleString('ru-RU')} сум`;
  return `${num.toLocaleString('uz-UZ')} so'm`;
};

export const formatNumber = (num) => {
  const locale = currentLang === 'en' ? 'en-US' : currentLang === 'ru' ? 'ru-RU' : 'uz-UZ';
  return Number(num || 0).toLocaleString(locale);
};

const WEEKDAYS_UZ = ['Yakshanba', 'Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba'];
const WEEKDAYS_RU = ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'];
const WEEKDAYS_EN = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

const MONTHS_UZ = ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr'];
const MONTHS_RU = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'];
const MONTHS_EN = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export const formatUzbekDate = (date = new Date()) => {
  const d = date instanceof Date ? date : new Date(date);
  const weekdays = currentLang === 'ru' ? WEEKDAYS_RU : currentLang === 'en' ? WEEKDAYS_EN : WEEKDAYS_UZ;
  const months = currentLang === 'ru' ? MONTHS_RU : currentLang === 'en' ? MONTHS_EN : MONTHS_UZ;
  return `${weekdays[d.getDay()]}, ${d.getDate()} ${months[d.getMonth()]}`;
};

/**
 * SQLite dan kelgan UTC vaqtini Toshkent vaqti (UTC+5) da formatlash
 */
export const formatTashkentDate = (dateStr, options = {}) => {
  if (!dateStr) return '';
  const normalized = dateStr.includes('Z') || dateStr.includes('+') || dateStr.includes('T')
    ? dateStr
    : dateStr.replace(' ', 'T') + 'Z';
  const date = new Date(normalized);
  if (isNaN(date.getTime())) return '';
  const defaultOptions = {
    timeZone: 'Asia/Tashkent',
    ...options,
  };
  const locale = currentLang === 'en' ? 'en-US' : currentLang === 'ru' ? 'ru-RU' : 'uz-UZ';
  return date.toLocaleString(locale, defaultOptions);
};

export const formatTashkentTime = (dateStr, options = {}) => {
  return formatTashkentDate(dateStr, {
    hour: '2-digit',
    minute: '2-digit',
    ...options,
  });
};

export const formatTashkentShort = (dateStr) => {
  return formatTashkentDate(dateStr, {
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  });
};
