export const UZ = {
  save: 'Saqlash',
  cancel: 'Bekor qilish',
  delete: "O'chirish",
  edit: "Tahrirlash",
  add: "Qo'shish",
  search: 'Qidirish...',
  loading: 'Yuklanmoqda...',
  noData: "Ma'lumot topilmadi",
  confirm: 'Tasdiqlash',
  actions: 'Amallar',
  total: 'Jami',
  status: 'Holat',
  active: 'Faol',
  inactive: 'Nofaol',
  all: 'Barchasi',
  close: 'Yopish',
  print: 'Chop etish',
  export: 'Eksport',
  filter: 'Filtrlash',
  back: 'Orqaga',
  yes: 'Ha',
  no: "Yo'q",
  confirmDelete: "O'chirishni tasdiqlaysizmi?",
  login: 'Kirish',
  logout: 'Chiqish',
  email: 'Elektron pochta',
  password: 'Parol',
  rememberMe: 'Eslab qolish',
  signIn: 'Tizimga kirish',
  signingIn: 'Kirilmoqda...',
  welcomeBack: 'Xush kelibsiz!',
  loginSubtitle: 'POS tizimiga kiring',
  demoCredentials: 'Demo: admin@pos.com / password',
  dashboard: 'Boshqaruv paneli',
  pos: 'Kassa',
  products: 'Mahsulotlar',
  sales: 'Sotuvlar',
  reports: 'Hisobotlar',
  settings: 'Sozlamalar',
  profile: 'Profil',
  inventory: 'Ombor',
  dashboardTitle: 'Boshqaruv paneli',
  dashboardSubtitle: "Xush kelibsiz! Biznesingiz haqida umumiy ma'lumot.",
  todayRevenue: 'Bugungi tushum',
  monthlyRevenue: 'Oylik tushum',
  totalProducts: 'Jami mahsulotlar',
  lowStock: 'Kam qoldi',
  transactions: 'tranzaksiya',
  inventoryValue: 'ombor qiymati',
  outOfStock: 'Tugadi',
  recentSales: 'Oxirgi sotuvlar',
  topProducts: 'TOP mahsulotlar',
  noSalesToday: 'Bugun sotuv yo\'q',
  weeklySales: 'Haftalik sotuvlar',
  productsTitle: 'Mahsulotlar',
  addProduct: "Mahsulot qo'shish",
  editProduct: 'Mahsulotni tahrirlash',
  productName: 'Mahsulot nomi',
  productCode: 'Kod',
  barcode: 'Shtrix-kod',
  category: 'Kategoriya',
  brand: 'Brend',
  purchasePrice: 'Sotib narxi',
  sellingPrice: 'Sotish narxi *',
  stockQuantity: 'Mavjud miqdor',
  minimumStock: 'Minimal zaxira',
  unit: "O'lchov birligi",
  description: 'Tavsif',
  noCategory: "Kategoriya yo'q",
  allCategories: 'Barcha kategoriyalar',
  labels: 'Yorliqlar',
  deleteProduct: "Mahsulotni o'chirish",
  deleteConfirm: "haqiqatan ham o'chirishni xohlaysizmi?",
  outOfStockStatus: 'Tugadi',
  lowStockStatus: 'Kam qoldi',
  inStockStatus: 'Mavjud',
  cart: 'Savat',
  clear: 'Tozalash',
  emptyCart: 'Savat bo\'sh',
  emptyCartHint: 'Mahsulot qidirib yoki skanerlang',
  scan: 'Skanerlash',
  searchOrScan: 'Qidirish yoki skanerlash...',
  each: 'dona',
  items: 'Mahsulotlar',
  proceedCheckout: "To'lovga o'tish",
  checkout: "To'lov",
  totalAmount: 'Jami summa',
  customerName: 'Mijoz nomi',
  walkInCustomer: "O'tib ketayotgan mijoz",
  paymentMethod: "To'lov usuli",
  cash: 'Naqd',
  card: 'Karta',
  other: 'Boshqa',
  receivedAmount: 'Qabul qilingan summa',
  change: 'Qaytim',
  completeSale: "Sotuvni yakunlash",
  processing: 'Qayta ishlanmoqda...',
  saleComplete: 'Sotuv tugallandi!',
  paymentSuccessful: "To'lov muvaffaqiyatli!",
  printReceipt: "Chekni chop etish",
  scanBarcode: "Shtrix-kodni skanerlash",
  pointCamera: "Kamerani shtrix-kodga yo'naltiring...",
  cameraError: "Kamera mavjud emas. Shtrix-kodni qo'lda kiriting.",
  notFound: 'Mahsulot topilmadi',
  notEnoughStock: 'Yetarli zaxira yo\'q',
  productAdded: "qo'shildi",
  insufficientStock: 'Zaxira yetarli emas',
  salesTitle: 'Sotuvlar tarixi',
  invoice: 'Hisob-faktura',
  customer: 'Mijoz',
  cashier: 'Kassir',
  amount: 'Summa',
  date: 'Sana',
  time: 'Vaqt',
  payment: "To'lov",
  view: "Ko'rish",
  fromDate: 'Dan',
  toDate: 'Gacha',
  allMethods: 'Barcha usullar',
  reportsTitle: 'Hisobotlar',
  analytics: "Tahlillar va ma'lumotlar",
  dailySales: 'Kunlik sotuvlar',
  monthlySales: 'Oylik sotuvlar',
  topSelling: 'TOP sotilganlar',
  inventoryReport: "Ombor hisoboti",
  totalSalesCount: 'Jami sotuvlar',
  totalRevenue: 'Jami tushum',
  paymentMethods: "To'lov usullari",
  salesList: 'Sotuvlar ro\'yxati',
  dailyRevenue: 'Kunlik tushum',
  monthlySummary: 'Oylik xulosa',
  topSellingProducts: "Eng ko'p sotilgan mahsulotlar",
  totalProductsReport: 'Jami mahsulotlar',
  stockValue: 'Zaxira qiymati',
  lowStockCount: 'Kam qoldi',
  outOfStockCount: 'Tugadi',
  inventoryList: 'Ombor ro\'yxati',
  settingsTitle: 'Sozlamalar',
  storeInfo: "Do'kon ma'lumotlari",
  storeName: "Do'kon nomi",
  phone: 'Telefon',
  address: 'Manzil',
  currencyTax: 'Valyuta va soliq',
  currency: 'Valyuta',
  symbol: 'Belgi',
  taxPercent: 'Soliq %',
  receiptSettings: 'Chek sozlamalari',
  receiptHeader: 'Chek yuqorisi',
  receiptFooter: 'Chek pasti',
  lowStockThreshold: 'Kam zaxira chegarasi',
  saveSettings: 'Sozlamalarni saqlash',
  settingsSaved: 'Sozlamalar saqlandi!',
  profileTitle: 'Profil',
  name: 'Ism',
  role: 'Rol',
  admin: 'Admin',
  cashier_role: 'Kassir',
  memberSince: "A'zo bo'lgan sana",
  notifications: 'Bildirishnomalar',
  noNotifications: "Bildirishnoma yo'q",
  lowStockAlert: 'Kam zaxira ogohlantirishi',
  productRunningLow: 'mahsulot kam qoldi',
  markAllRead: "Barchasini o'qilgan deb belgilash",
  daily: 'Kunlik',
  weekly: 'Haftalik',
  monthly: 'Oylik',
  receipt: 'Chek',
  subtotal: 'Oraliq yig\'indisi',
  tax: 'Soliq',
  pcs: 'dona',
  kg: 'kg',
  g: 'gram',
  l: 'litr',
  ml: 'ml',
  box: 'quti',
  bag: 'xalta',
  bottle: 'butulka',
  jar: 'idish',
  pack: 'payket',
  soom: "so'm",
};

export const formatCurrency = (amount) => {
  const num = Number(amount || 0);
  return `${num.toLocaleString('uz-UZ')} so'm`;
};

export const formatNumber = (num) => {
  return Number(num || 0).toLocaleString('uz-UZ');
};
